### PR TITLE
Encode version 1 in layers

### PR DESCRIPTION
**Pull request by rmarianski**
Connects to https://github.com/mapzen/mapbox-vector-tile/issues/42

@zerebubuth could you review please?

### CODE REVIEW

**Comment by rmarianski** [comment]
Thinking about this a little bit more, could it have consequences in tangram wrt the multipolygon winding order changes?

**Comment by zerebubuth** [comment]
As far as I can tell from [Tangram's decoder](https://github.com/tangrams/tangram/blob/master/src/sources/mvt.js), it isn't checking the version, so I think we're safe to "downgrade" to v1 for the moment.

**Comment by zerebubuth** [comment]
:+1:

**Comment by rmarianski** [comment]
Cool. I forgot that tangram itself was handling [decoding multipolygons](https://github.com/tangrams/tangram/blob/3abd09cbf0dcfbab020783008a0ce9eb68de830b/src/sources/mvt.js#L73).

**Pull request merged**
