### PR TITLE
Travis intergration

### PR DESCRIPTION
**Pull request by loicgasser**
Hi!

I just prepared a small PR to integrate travis and coverage in you project.

https://github.com/loicgasser/mapbox-vector-tile (for an example)

You simply need to activate the project in (free for open-source projects)
https://travis-ci.org/mapzen/mapbox-vector-tile (Travis)
https://coveralls.io/github/mapzen/mapbox-vector-tile?branch=master (Coveralls)

This will ensure that:
1) Coverage won't decrease over time (current coverage at 84%)
2) Python 2.6, 2.7 and 3.5 are always tested
3) Every pull request triggers a build (like now with circle)

Let me know if you guys enjoy it.

### CODE REVIEW

**Comment by loicgasser** [comment]
Tests actually fail with python 2.6, I'll try to fix.

**Comment by loicgasser** [comment]
Ok so unittest module for python 2.6 uses different methods ```failUnless``` instead of ```assertInt``` for instance. So it cannot be tested and I removed this python version.

**Comment by rmarianski** [comment]
Thanks!

**Comment by loicgasser** [comment]
cool, I think you still need to activate travis and coverage for this project.

**Comment by nvkelso** [comment]
Done!

**Pull request merged**
