### PR TITLE
First draft of better docs for #12

### PR DESCRIPTION
**Pull request by ezheidtmann**
Please review carefully. In particular:

 * Not sure if a point at 4096 would be considered part of the tile or not (i.e. are tiles [0, 4096] or [0, 4096) ? )
 * Did I get the coordinate system orientation correct?

### CODE REVIEW

**Comment by ezheidtmann** [comment]
Updated summary with questions for review. Thanks yall!

**Comment by rmarianski** [comment]
Hey @ezheidtmann, thanks! And apologies for the late response.

> * Not sure if a point at 4096 would be considered part of the tile or not (i.e. are tiles [0, 4096] or [0, 4096) ? )

I think [0, 4096) would be more accurate, but I'm not 100% sure.

> Did I get the coordinate system orientation correct?

Yes. That's the system that we use and it looks to inter-operate fine.

I think this is good to merge in, maybe with a change from [0, 4096] -> [0, 4096)

@hkrishna, @bcamper: any feedback before merging?

**Comment by bcamper** [comment]
@ezheidtmann thanks for your contribution.

When documenting tile extents, we should keep in mind that the `extents` is often set to 4096 by convention, but [according to the spec](https://github.com/mapbox/vector-tile-spec/tree/master/1.0.1), it can be set to any range.

It also indicates that it is exclusive, e.g. [0, 4096): https://github.com/mapbox/vector-tile-spec/blob/master/1.0.1/vector_tile.proto#L91

**Comment by rmarianski** [comment]
@ezheidtmann thanks again for the update!

**Pull request merged**
