### PR TITLE
Very basic python3 compliancy

### PR DESCRIPTION
**Pull request by yohanboniface**
Just a bunch of relative imports.

### CODE REVIEW

**Comment by yohanboniface** [comment]
Those changes allow me to use python 3.4 without issues (until now :p ).
Tests are not passing, mainly because properties (which is a dict) are not deterministic (so foo comes sometimes before bar, sometimes after, etc.), and thus the output bytes change at every run. That's a bit annoying, not sure how to have strong tests then.

It's supposed to be fully compatible with the current python 2 version.

**Comment by rmarianski** [comment]
Thanks for the effort and the update here! The tests worked for me in a python2 setting. With python3, I did see some of the failures you mentioned about bytes not matching, but I also see some other ones as well. Some look like python 2 and 3 incompatibilities, but the decoding test seemed to fail too. Do you get those too? Or is it something in my environment? Here's the trace from my end:

https://gist.github.com/rmarianski/99a2d6e16b6cad4f9313

About the testing strategy and checking if the bytes match, my preference is to have a very simple test, perhaps a feature with just a single property that checks that encoding the simplest input works. And maybe the same for decode. And then, I'd prefer to just have round trip tests to exercise the other cases that would encode the source data, decode it, and then verify that the result matches expectations based on the input.

Another option would be to have the encoder sort the properties before encoding them. I don't like that because it would add some overhead. Or maybe instead of doing that in the encoder, the tests could use their our own implementation of a dict like interface that returns the properties in the same order across python versions (probably just by sorting them first)

We could also consider changing the contract of the api to take a sequence of tuples instead of a dict, but that doesn't sound great to me either.

I think that transitioning most of the tests to be in a round trip style would make them more resilient to changes too, so I'd prefer to go down that route. If that sounds good to you, the testing work can be done in a separate pr, and then if the python3 work is rebased on top of that, the tests should theoretically all pass.

**Comment by yohanboniface** [comment]
>  but I also see some other ones as well. Some look like python 2 and 3 incompatibilities, but the 
> decoding test seemed to fail too. Do you get those too? Or is it something in my environment? 
> Here's the trace from my end:

Yep, I have them too :)

> I'd prefer to just have round trip tests to exercise the other cases that would encode the source data, 
> decode it, and then verify that the result matches expectations based on the input.

Sounds good to me, I'll make a proposal this way :)

**Comment by yohanboniface** [comment]
Also, there are a bunch of pep8 fixes needed, do you want me to include them in this PR (but in dedicated commit), or should I refrain my pep8-compultion to another PR? :)

**Comment by rmarianski** [comment]
I'd prefer that the pep8 changes be done separately. I myself have been holding off on doing a sweeping change, but if you want to just make everything pep8 compliant first, and then base all these other changes off that, that sounds great to me. I don't know of any outstanding branches or changes currently floating around, so I don't think it'll be disruptive to do now. I can also add in a circleci task that will enforce pep8 compliance going forward.

Or if it's easier because you've already done some work here, after these branches/prs get merged a separate pass can be made to make everything pep8 compliant.

**Comment by yohanboniface** [comment]
@rmarianski what do you think of last commit?

**Comment by rmarianski** [comment]
Looks good to me. Ok for me to merge to master?

I'm thinking of adding a more explicit requirement in setup.py for the protobuf alpha, because otherwise it didn't work for me with python3. ie: `protobuf>=3.0.0a3`.

**Comment by yohanboniface** [comment]
> I'm thinking of adding a more explicit requirement in setup.py for the protobuf alpha, because 
> otherwise it didn't work for me with python3. ie: protobuf>=3.0.0a3.

This choice is up to you, depending on whether you want to have a dependency on the alpha package. I think all the vector tile stack is sort of alpha at the end so I'd not mind going this way myself, but that's your choice :)

**Comment by rmarianski** [comment]
I'll leave it the way it is at the moment then, since I tried it locally and pip preferred to get the alpha 1 version anyway which didn't end up working for me.

**Comment by rmarianski** [comment]
Just merged the changes in, thanks!

**Pull request merged**
